# Generated by Django 5.2.4 on 2025-07-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'SuperAdmin'), ('nurse', 'Nurse'), ('doctor', 'Doctor'), ('lab', 'Lab Technician'), ('pharmacy', 'Pharmacy'), ('records', 'Medical Records'), ('physiotherapist', 'Physiotherapist')], default='superadmin', max_length=30),
        ),
    ]
